IF (${TOOL_CHAIN} MATCHES "x86")
    message("[32mBuilding from linux terminal[0m")
    include(x86)
elseif(${TOOL_CHAIN} MATCHES "esp32")
    message("[32mBuilding from external terminal - Generate hex file[0m")
elseif(${TOOL_CHAIN} MATCHES "win")
    message("${ESCAPE}[34m Building from VSCode - Generate simulate file${ESCAPE} [0m")
else()
    message("Building from external terminal - vscode default")
ENDIF()