
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(CMAKE_C_COMPILER         "/usr/bin/gcc")
set(CMAKE_CXX_COMPILER       "/usr/bin/g++")
set(CMAKE_STRIP              "/usr/bin/strip")

set(CMAKE_FIND_ROOT_PATH     ${CMAKE_FIND_ROOT_PATH} "/")
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NERVER)
